# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: word_parser.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11word_parser.proto\x12\nwordparser\"#\n\x0bWordRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"$\n\x0cWordResponse\x12\x14\n\x0cjson_content\x18\x01 \x01(\t2N\n\nWordParser\x12@\n\tParseWord\x12\x17.wordparser.WordRequest\x1a\x18.wordparser.WordResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'word_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDREQUEST']._serialized_start=33
  _globals['_WORDREQUEST']._serialized_end=68
  _globals['_WORDRESPONSE']._serialized_start=70
  _globals['_WORDRESPONSE']._serialized_end=106
  _globals['_WORDPARSER']._serialized_start=108
  _globals['_WORDPARSER']._serialized_end=186
# @@protoc_insertion_point(module_scope)
